apiVersion: v1
kind: ConfigMap
metadata:
  name: api-configs
  namespace: zimit
data:
  ZIM_EXPIRATION: "7"
  LOGS_EXPIRATION: "7"
  ZIMFARM_DISALLOW_CAPABILITIES: "y"
  ZIMIT_USE_RELAXED_SCHEMA: "y"
  NAUTILUS_USE_RELAXED_SCHEMA: "y"
  # Timeout for requests to other services
  REQ_TIMEOUT_NOTIFICATIONS: "10"
  REQ_TIMEOUT_CMS: "50"
  REQ_TIMEOUT_GHCR: "10"
  # Default publisher to set in ZIMs
  DEFAULT_PUBLISHER: "openZIM"
  ALLOWED_ORIGINS: https://farm.zimit.kiwix.org,https://zimit.kiwix.org
  BLOB_PRIVATE_STORAGE_URL: https://drive.zimit.kiwix.org/blobs
  BLOB_PUBLIC_STORAGE_URL: https://drive.zimit.kiwix.org/blobs
  BLOB_STORAGE_USERNAME: admin
  BLOB_MAX_SIZE: 1MB
  DELETE_ORPHANED_BLOBS_INTERVAL: 24h
