apiVersion: v1
kind: ConfigMap
metadata:
  name: farm-ui-configs
  namespace: zimit
data:
  config.json: |
    {
      "ZIMFARM_ZIM_DOWNLOAD_URL": "https://s3.us-west-1.wasabisys.com/org-kiwix-zimit",
      "ZIMFARM_WEBAPI": "https://api.farm.zimit.kiwix.org/v2",
      "MATOMO_ENABLED": false,
      "BLOB_MAX_SIZE": 1048576
    }

