apiVersion: v1
kind: ConfigMap
metadata:
  name: farm-ui-configs
  namespace: zimit
data:
  ZIMFARM_KIWIX_DOWNLOAD_URL: "https://s3.us-west-1.wasabisys.com/org-kiwix-zimit"
  ZIMFARM_WEBAPI: "https://api.farm.zimit.kiwix.org/v1"
  ZIMFARM_LOGS_URL: "https://s3.us-west-1.wasabisys.com/org-kiwix-zimit"
  ZIMFARM_TASKS_LOAD_SCHEDULES_CHUNK_SIZE: "5"
  ZIMFARM_TASKS_LOAD_SCHEDULES_DELAY: "100"
