apiVersion: v1
kind: ConfigMap
metadata:
  name: ory-admin-ui-prod-configs
  namespace: login
data:
  IS_ORY_NETWORK: "true"
  KRATOS_PUBLIC_URL: "https://login.kiwix.org"
  KRATOS_ADMIN_URL: "https://login.kiwix.org"
  HYDRA_PUBLIC_URL: "https://login.kiwix.org"
  HYDRA_ADMIN_URL: "https://login.kiwix.org"
  NEXT_PUBLIC_APP_URL: "http://localhost:3000"