apiVersion: v1
kind: ConfigMap
metadata:
  name: db-configs
  namespace: cms
data:
  init-extensions.sh: |
    #!/bin/bash
    set -e

    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
        CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
    EOSQL
