apiVersion: v1
kind: ConfigMap
metadata:
  name: status-configs
  namespace: zimfarm
data:
  DEBUG: "F"
  REQUESTS_TIMEOUT: 30s
  ZIMFARM_API_URL: https://api.farm.openzim.org/v2
  ZIMFARM_FRONTEND_URL: https://farm.openzim.org
  ZIMFARM_USERNAME: healthcheck


