apiVersion: v1
kind: ConfigMap
metadata:
  name: status-configs
  namespace: zimfarm
data:
  DEBUG: "Y"
  REQUESTS_TIMEOUT: 30s
  ZIMFARM_API_URL: https://api.farm.openzim.org
  ZIMFARM_USERNAME: healthcheck


