apiVersion: v1
kind: ConfigMap
metadata:
  name: drive-configs
  namespace: zimfarm
data:
  custom.conf: |
    add_header Access-Control-Allow-Origin "https://farm.openzim.org" always;
    add_header Access-Control-Allow-Methods "GET, OPTIONS" always;
