apiVersion: v1
kind: ConfigMap
metadata:
  name: status-configs
  namespace: cms
data:
  CMS_FRONTEND_URL: https://cms.openzim.org
  CMS_USERNAME: healthcheck
  CMS_API_URL: https://api.cms.openzim.org/v1


