apiVersion: v1
kind: ConfigMap
metadata:
  name: ui-configs
  namespace: zimfarm
data:
  config.json: |
    {
      "ZIMFARM_ZIM_DOWNLOAD_URL": "https://mirror.download.kiwix.org/zim",
      "ZIMFARM_WEBAPI": "https://api.farm.openzim.org/v2",
      "MATOMO_ENABLED": true,
      "MATOMO_HOST": "https://stats.kiwix.org",
      "MATOMO_SITE_ID": 8,
      "MATOMO_TRACKER_FILE_NAME": "matomo",
      "MONITORING_URL": "https://monitoring.openzim.org/v3"
    }
