apiVersion: v1
kind: ConfigMap
metadata:
  name: ui-configs
  namespace: cms
data:
  config.json: |
    {
      "CMS_API": "https://api.cms.openzim.org/v1",
      "OAUTH_BASE_URL": "https://login.kiwix.org",
      "LOGIN_MODES": ["oauth"]
    }

