apiVersion: v1
kind: ConfigMap
metadata:
  name: status-configs
  namespace: zimit
data:
  DEBUG: "F"
  REQUESTS_TIMEOUT: 30s
  ZIMFARM_API_URL: https://api.farm.zimit.kiwix.org/v2
  ZIMFARM_FRONTEND_URL: https://farm.zimit.kiwix.org
  ZIMFARM_USERNAME: healthcheck


